<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;

/** @var Logo $block */
/** @var Escaper $escaper */

$storeName = $block->getThemeName() ?: $block->getLogoAlt()
?>
<div class="z-20 order-3 xl:order-1 max-w-6 sm:absolute sm:left-30 xl:left-10 xl:max-w-1/2 header-logo">
    <a class="flex items-center justify-center text-xl font-medium tracking-wide text-gray-800
        no-underline hover:no-underline font-title"
       href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
       title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
       aria-label="store logo">
        <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
             title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ?
                'width="' . $escaper->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
            <?= $block->getLogoHeight() ?
                'height="' . $escaper->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
        />
        <?= $escaper->escapeHtml($storeName) ?>
    </a>
</div>
