<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SearchHelper $helper */

$helper = $this->helper(SearchHelper::class);

/** @var \Hyva\Theme\ViewModel\SvgIcons $icons */
$icons = $viewModels->require(\Hyva\Theme\ViewModel\SvgIcons::class);
?>
<div class="container py-2.5 mx-auto text-black sm:py-5 xl:my-5 xl:p-0">
    <form class="form minisearch" id="search_mini_form"
          action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <input id="search"
               x-ref="searchInput"
               type="search"
               name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
               value="<?= $escaper->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
               placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
               maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
               class="w-full px-9 py-2 h-10 text-base transition duration-300 ease-out appearance-none border border-westar text-wood rounded-3xl focus:outline-none focus:border-concord focus:shadow-none xl:pl-5 xl:pr-12"
        />
        <button class="flex items-center justify-center pointer-events-none text-wood-light transition duration-300 ease-out w-9 h-10 absolute top-2.5 left-5 hover:text-black sm:top-5 sm:left-10 xl:left-auto xl:right-1 xl:w-10 xl:pointer-events-auto" type="submit">
            <?= $icons->searchHtml(
                "w-4.5 h-4.5 fill-current text-current xl:w-5 xl:h-5",
                18,
                18
            ) ?>
        </button>
    </form>
</div>
