<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
// use Hyva\Theme\ViewModel\BlockCache;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */
/** @var BlockCache $blockCacheViewModel */

$productViewModel    = $viewModels->require(ProductPage::class);
// $blockCacheViewModel = $viewModels->require(BlockCache::class);

$productCollection = $block->getLoadedProductCollection();
?>
<?php if (!$productCollection->count()):?>
    <div class="message info empty">
        <div>
            <?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    </div>
<?php else:?>
<section class="py-8">
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper mode-<?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <div class="mx-auto pt-4 pb-12 grid gap-4 <?= $viewMode === 'grid' ? 'sm:grid-cols-2 xl:grid-cols-3' : 'grid-cols-1' ?>">
            <?php /** @var \Magento\Catalog\Model\Product $product */ ?>
            <?php foreach ($productCollection as $product):
            $itemCacheKeyInfo = [
                $product->getId(),
                $viewMode,
                $templateType,
                $block->getTemplate(),
                $product->getStoreId(),
                $productViewModel->getCurrencyData()['code']
            ];
            ?>
                <?= $block->getLayout()->getBlock('product_list_item')
                    ->setData('product', $product)
                    ->setData('view_mode', $viewMode)
                    ->setData('image_display_area', $imageDisplayArea)
                    ->setData('show_description', $showDescription)
                    ->setData('position', $pos)
                    ->setData('pos', $pos)
                    ->setData('template_type', $templateType)
                    ->setData('cache_lifetime', 3600)
                    ->setData('cache_tags', $product->getIdentities())
                    // ->setData('cache_key', $blockCacheViewModel->hashCacheKeyInfo($itemCacheKeyInfo))
                    ->toHtml(); ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?= $block->getToolbarHtml() ?>
</section>
<?php endif; ?>
