<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>

<div class="mb-2.5 mt-12 p-5 md:mt-16 md:grid md:grid-rows-2 md:grid-flow-col md:gap-0 lg:p-10 home-content-blocks">
    <div class="md:col-span-3 md:row-span-1 md:row-start-1 md:flex md:items-end content-top-blocks">
        <div class="h-48 sm:h-auto md:w-1/3 cms-home-block-1">
            <p class="h-full">
                <a class="block h-full w-full" href="https://www.icko-apiculture.com/catalogues-icko" target="_self">
                    <img class="h-full mx-auto object-cover w-auto md:h-auto md:w-full" src="https://www.icko-apiculture.com/media/wysiwyg/bloc-home-page1.jpg" alt="Nos Catalogues" width="380" height="360">
                </a>
            </p>
        </div>
        <div class="h-52 sm:h-auto md:w-2/3 cms-home-block-2">
            <p class="h-full">
                <a class="block h-full w-full" href="https://www.icko-apiculture.com/au-rucher/outils-apiculteur/vetements-apiculteur.html">
                    <picture>
                        <source srcset="https://www.icko-apiculture.com/media/amasty/amoptmobile/wysiwyg/Home_page_2_copie.jpg" media="(max-width: 480px)">
                        <source srcset="https://www.icko-apiculture.com/media/wysiwyg/Home_page_2_copie.jpg">
                        <img class="h-full mx-auto object-cover w-auto md:h-auto md:w-full" src="https://www.icko-apiculture.com/media/wysiwyg/Home_page_2_copie.jpg" alt="" width="760" height="440">
                    </picture>
                </a>
            </p>
        </div>
    </div>
    <div class="md:col-span-3 md:row-span-1 md:row-start-2 md:flex md:items-start content-left-blocks">
        <div class="h-36 sm:h-auto md:w-2/3 cms-home-block-4">
            <p class="h-full">
                <a class="block h-full w-full" href="/l-univers-du-debutant.html" title="L'univers du débutant">
                    <img class="h-full mx-auto object-cover w-auto md:h-auto md:w-full" src="https://www.icko-apiculture.com/media/wysiwyg/content/icko_univers_debutant.jpg" alt="Univers du débutant">
                </a>
            </p>
        </div>
        <div class="nosto_element" id="frontpage-nosto-2"></div>
    </div>
    <div class="md:col-span-1 md:row-span-2 md:row-start-1 md:flex md:flex-wrap md:content-start md:items-start md:pt-5 2xl:pt-10 content-right-blocks">
        <div class="h-40 sm:h-auto md:w-full cms-home-block-3">
            <p class="h-full">
                <a class="block h-full w-full" href="https://www.icko-apiculture.com/au-rucher/suivi/frelons-et-coleopteres.html">
                    <img class="h-full mx-auto object-cover w-auto md:h-auto md:w-full" src="https://www.icko-apiculture.com/media/wysiwyg/CAPTURE_FRELON.jpg" alt="" width="381" height="320">
                </a>
            </p>
        </div>
        <div class="h-48 sm:h-auto md:w-full cms-home-block-5">
            <p class="h-full">
                <a class="block h-full w-full" href="https://www.icko-apiculture.com/api-ete-2021" title="API.ÉTÉ">
                    <img class="h-full mx-auto object-cover w-auto md:h-auto md:w-full" src="https://www.icko-apiculture.com/media/wysiwyg/OP_API_ETE.jpg" alt="API.ÉTÉ" width="381" height="320">
                </a>
            </p>
        </div>
    </div>
</div>