<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var \Hyva\Theme\ViewModel\SvgIcons $icons */
$icons = $viewModels->require(\Hyva\Theme\ViewModel\SvgIcons::class);
?>

<div class="mb-20 px-5 md:flex lg:px-10 home-icko-focus">
    <div class="mx-auto max-w-full text-center w-80 lg:w-90 xl:w-110 icko-focus-left">
        <div class="mb-9 md:ml-5 md:pt-12.5 md:relative md:text-left md:w-full md:z-10 lg:ml-10 focus-title">
            <div class="focus-title-inner">
                <div class="font-bold text-2xl md:border-b md:border-wood md:mb-4 md:pb-1 md:leading-10 md:text-2lg title-text">
                    <span>ICKO Apiculture</span>
                </div>
                <div class="italic text-xs lg:text-2xs sub-title-text">Auprès des ruches et des apiculteurs depuis 3 générations</div>
            </div>
        </div>
        <div class="relative focus-magasin">
            <div class="px-5 md:px-0 f-m-images">
                <a class="block" title="" href="/storelocator">
                    <img class="opacity-90" src="https://www.icko-apiculture.com/media/wysiwyg/pict-focus.jpg" alt="" width="440" height="320">
                </a>
            </div>
            <div class="absolute -bottom-5 w-full md:px-5 lg:px-10 f-m-button">
                <a title="" href="/storelocator">
                    <button class="bg-wood font-bold rounded-3xl px-5 py-3 text-center text-white tracking-widest uppercase w-full">
                        <span>trouver <span class="text-yellow-400">nos magasins</span></span>
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="mt-15 md:mt-0 md:w-full-80 lg:w-full-90 xl:w-full-110 icko-focus-right">
        <div class="relative md:-ml-10 focus-img">
            <p>
                <a href="#">
                    <img src="https://www.icko-apiculture.com/media/wysiwyg/pic-2.jpg" alt="">
                    <span class="absolute font-bold left-1/2 text-white -top-2.5 tracking-widest transform -translate-x-1/2 uppercase whitespace-nowrap md:bottom-9 md:left-20 md:top-auto md:transform-none focus-text">Découvrir ICKO</span>
                    <span class="absolute bg-wood border-2 border-white flex justify-center h-10 items-center left-1/2 rounded-3xl top-1/2 transform -translate-x-1/2 -translate-y-1/2 w-10 md:h-20 md:rounded-full md:w-20 focus-play">
                        <?= $icons->playHtml("w-5 h-5 fill-current ml-1 text-white md:w-10 md:h-10 md:ml-2", 16, 20) ?>
                    </span>
                </a>
            </p>
        </div>
        <div class="max-w-90 mx-auto px-5 pt-6 w-full md:px-10 focus-content">
            <div class="pb-5 content-text">De part notre position de leader, nous considérons qu’il est de notre devoir de défendre les droits des apiculteurs et de se battre pour l’amélioration de leurs conditions de travail. Avec les changements environnementaux actuels, les apiculteurs sont aujourd’hui les garants de la reproduction des abeilles. C’est donc également notre rôle de veiller à leur survie..&nbsp; &nbsp; &nbsp;&nbsp;</div>
            <div class="content-link">
                <a class="block font-bold pl-10 relative text-yellow-500 tracking-widest uppercase" href="/nos-engagements">
                    <span>Découvrir nos engagements</span>
                </a>
            </div>
        </div>
    </div>
    <div id="popup-youtube" style="display:none;">
        <iframe width="640" height="360" src="https://www.youtube.com/embed/hIhCCFUjHwU?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
    </div>
</div>