<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>

<div class="home-icko-focus">
    <div class="icko-focus-left">
        <div class="focus-title">
            <div class="focus-title-inner">
                <div class="title-text"><span>ICKO Apiculture</span></div>
                <div class="sub-title-text">Auprès des ruches et des apiculteurs depuis 3 générations</div>
            </div>
        </div>
        <div class="focus-magasin">
            <div class="f-m-images">
                <a title="" href="/storelocator"><img src="https://www.icko-apiculture.com/media/wysiwyg/pict-focus.jpg" alt="" width="440" height="320"></a>
            </div>
            <div class="f-m-button">
                <a title="" href="/storelocator">
                    <button>
                        <span>trouver <span>nos magasins</span></span>
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="icko-focus-right">
        <div class="focus-img">
            <p>
                <a href="#">
                    <img src="https://www.icko-apiculture.com/media/wysiwyg/pic-2.jpg" alt="">
                    <span class="focus-text">Découvrir ICKO</span>
                    <span class="focus-play"><i class="icon-play"></i></span>
                </a>
            </p>
        </div>
        <div class="focus-content">
            <div class="content-text">De part notre position de leader, nous considérons qu’il est de notre devoir de défendre les droits des apiculteurs et de se battre pour l’amélioration de leurs conditions de travail. Avec les changements environnementaux actuels, les apiculteurs sont aujourd’hui les garants de la reproduction des abeilles. C’est donc également notre rôle de veiller à leur survie..&nbsp; &nbsp; &nbsp;&nbsp;</div>
            <div class="content-link">
                <a href="/nos-engagements">
                    <span>Découvrir nos engagements</span>
                </a>
            </div>
        </div>
    </div>
    <div id="popup-youtube" style="display:none;">
        <iframe width="640" height="360" src="https://www.youtube.com/embed/hIhCCFUjHwU?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
    </div>
</div>