<div class="p-5 mb-10 md:mb-20 home-retrieve-post">
	<h3 class="font-bold text-2xl text-center leading-10 mb-8 relative block-title">
		<span>Articles du blog</span>
		<span class="absolute bg-wood block -bottom-13 left-1/2 h-10 w-px"></span>
	</h3>
	<div class="block-content-retrieve">
		<ul class="md:flex md:justify-between">
			<li>
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 sm:h-50 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2021/07/abeille-tournesol-1024x683.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>Lorem ipsum dolor</span>
							</h4>
							<div class="box-retrieve-description">
								Sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud...
							</div>
						</div>
						<div class="box-retrieve-link">
							<button><span>Lire la suite</span> <i class="icon-right-arr"></i></button>
						</div>
					</a>
				</div>
			</li>
			<li class="hidden md:block">
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 sm:h-50 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2020/01/pot-miel-1024x768.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>Sed do eiusmod tempor</span>
							</h4>
							<div class="box-retrieve-description">
								Incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea consequat...
							</div>
						</div>
						<div class="box-retrieve-link">
							<button><span>Lire la suite</span> <i class="icon-right-arr"></i></button>
						</div>
					</a>
				</div>
			</li>
			<li class="hidden 2xl:block">
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 sm:h-50 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2020/05/bourrache-abeille.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>dolor sit amet</span>
							</h4>
							<div class="box-retrieve-description">
								dolor sit amet
								Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua laboris nisi ut aliquip ex ea commodo...
							</div>
						</div>
						<div class="box-retrieve-link">
							<button><span>Lire la suite</span> <i class="icon-right-arr"></i></button>
						</div>
					</a>
				</div>
			</li>
		</ul>
	</div>
	<div class="link-to-retrieve">
		<a href="#" target="_blank"><span>Décotuvrir le blog</span> </a>
	</div>
</div>
