<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var \Hyva\Theme\ViewModel\SvgIcons $icons */
$icons = $viewModels->require(\Hyva\Theme\ViewModel\SvgIcons::class);
?>

<div class="p-5 mb-10 md:mb-20 md:px-0 xl:px-5 home-retrieve-post">
	<h3 class="font-bold text-2xl text-center leading-10 mb-8 relative lg:text-2lg block-title">
		<span>Articles du blog</span>
		<span class="absolute bg-wood block -bottom-13 left-1/2 h-10 w-px"></span>
	</h3>
	<div class="mb-7.5 block-content-retrieve">
		<ul class="md:flex md:justify-between">
			<li class="w-full md:px-10 md:w-1/2 lg:px-15">
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 overflow-hidden sm:h-50 xl:h-60 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2021/07/abeille-tournesol-1024x683.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 md:bg-white md:relative md:-top-10 lg:px-10 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>Lorem ipsum dolor</span>
							</h4>
							<div class="md:h-20 md:overflow-hidden box-retrieve-description">
								Sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud...
							</div>
						</div>
						<div class="mt-4 box-retrieve-link">
							<button class="bg-wood flex items-center justify-between rounded-3xl font-bold text-white uppercase h-10 px-8 tracking-widest w-full">
								<span>Lire la suite</span>
								<span>
									<?= $icons->rightArrHtml(
										"w-6 h-2.5 fill-current text-current opacity-60", 24, 10
									) ?>
								</span>
							</button>
						</div>
					</a>
				</div>
			</li>
			<li class="hidden w-full md:block md:px-10 md:w-1/2 lg:px-15">
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 overflow-hidden sm:h-50 xl:h-60 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2020/01/pot-miel-1024x768.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 md:bg-white md:relative md:-top-10 lg:px-10 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>Sed do eiusmod tempor</span>
							</h4>
							<div class="md:h-20 md:overflow-hidden box-retrieve-description">
								Incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea consequat...
							</div>
						</div>
						<div class="mt-4 box-retrieve-link">
							<button class="bg-wood flex items-center justify-between rounded-3xl font-bold text-white uppercase h-10 px-8 tracking-widest w-full">
								<span>Lire la suite</span>
								<span>
									<?= $icons->rightArrHtml(
										"w-6 h-2.5 fill-current text-current opacity-60", 24, 10
									) ?>
								</span>
							</button>
						</div>
					</a>
				</div>
			</li>
			<li class="hidden w-full md:px-10 md:w-1/2 lg:px-15 2xl:block">
				<div class="box-retrieve">
					<a href="#" target="_blank">
						<div class="h-40 overflow-hidden sm:h-50 xl:h-60 box-retrieve-img">
							<img class="h-full w-auto mx-auto object-center" width="700" height="400" loading="lazy" src="https://blog.icko-apiculture.com/wp-content/uploads/2020/05/bourrache-abeille.jpg" alt="" >
						</div>
						<div class="pt-8 px-5 md:bg-white md:relative md:-top-10 lg:px-10 box-retrieve-info">
							<h4 class="font-bold tracking-widest uppercase box-retrieve-title">
								<span>dolor sit amet</span>
							</h4>
							<div class="md:h-20 md:overflow-hidden box-retrieve-description">
								dolor sit amet
								Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua laboris nisi ut aliquip ex ea commodo...
							</div>
						</div>
						<div class="mt-4 box-retrieve-link">
							<button class="bg-wood flex items-center justify-between rounded-3xl font-bold text-white uppercase h-10 px-8 tracking-widest w-full">
								<span>Lire la suite</span>
								<span>
									<?= $icons->rightArrHtml(
										"w-6 h-2.5 fill-current text-current opacity-60", 24, 10
									) ?>
								</span>
							</button>
						</div>
					</a>
				</div>
			</li>
		</ul>
	</div>
	<div class="text-center link-to-retrieve">
		<a class="font-bold inline-block relative text-yellow-500 tracking-widest uppercase" href="#" target="_blank">
			<span class="absolute bg-westar block h-px w-5 -left-10 top-1/2"></span>
			<span>Décotuvrir le blog</span>
			<span class="absolute bg-westar block h-px w-5 -right-10 top-1/2"></span>
		</a>
	</div>
</div>
