<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="text-concord bg-wildsand mt-5 py-5 md:py-15 footer-inner">
    <div class="container px-5 mx-auto lg:px-10">
        <div class="flex flex-wrap justify-center">
            <?= $block->getChildHtml() ?>
        </div>
    </div>
</div>

