<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div class="flex justify-center mb-8 order-8 w-full md:justify-start lg:max-w-screen-lg footer-avis-verifies">
    <img class="logo-avis-verifies" src="<?= $this->getViewFileUrl('images/logo-avis-verifies.png'); ?>" width="147" height="33" loading="lazy" alt="" />
    <meta class="netreviewsWidget" id="netreviewsWidgetNum147" data-jsurl="//cl.avis-verifies.com/fr/cache/a/d/a/adaed8b8-bc00-0d44-79c0-d2b9d9540563/widget4/widget03-147_script.js"/>
</div>