<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\UrlBuilder;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);

/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);
?>

<script>
    function menuAccordion() {
        return {
            open: false,
            toogle() {
                this.open = ! this.open
            }
        }
    }
</script>

<div class="w-full flex flex-wrap mb-8 px-5 md:px-0 md:w-3/4 lg:max-w-3xl lg:w-7/10 footer-menu">
    <div class="w-full md:grid md:grid-cols-2 md:gap-5">
        <div class="text-concord footer-links" x-data="menuAccordion()">
            <h4 class="flex items-center justify-between text-current relative font-bold uppercase py-3 md:pointer-events-none md:text-concord"
                @click="toogle()"
            >
                <?= $escaper->escapeHtml(__('Company')) ?>
                <span class="md:hidden"
                    :class="{
                        'hidden' : open === false,
                        'block' : open === true,
                    }"
                >
                    <?= $heroicons->chevronUpHtml('w-4 h-4 stroke-current text-current', 16, 16) ?>
                </span>
                <span class="md:hidden"
                    :class="{
                        'hidden' : open === true,
                        'block' : open === false,
                    }"
                >
                    <?= $heroicons->chevronDownHtml('w-4 h-4 stroke-current text-current', 16, 16) ?>
                </span>
            </h4>
            <ul class="md:block"
                x-show="open"
            >
                <li class="mb-2">
                    <a href="#" class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('About')) ?>
                    </a>
                </li>
                <li class="mb-2">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
                        class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('My Account')) ?>
                    </a>
                </li>
                <?php if (!$customer->customerLoggedIn()): ?>
                <li class="mb-2">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('sales/guest/form')) ?>"
                        class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('Orders and Returns')) ?>
                    </a>
                </li>
                <?php endif; ?>
                <li class="mb-2">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>"
                        class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('Contact')) ?>
                    </a>
                </li>
            </ul>
        </div>
        <div class="border-t border-westar text-concord md:border-0 footer-links" x-data="menuAccordion()">
            <h4 class="flex items-center justify-between text-current relative font-bold uppercase py-3 md:pointer-events-none md:text-concord"
                @click="toogle()"
            >
                <?= $escaper->escapeHtml(__('Legal')) ?>
                <span class="md:hidden"
                    :class="{
                        'hidden' : open === false,
                        'block' : open === true,
                    }"
                >
                    <?= $heroicons->chevronUpHtml('w-4 h-4 stroke-current text-current', 16, 16) ?>
                </span>
                <span class="md:hidden"
                    :class="{
                        'hidden' : open === true,
                        'block' : open === false,
                    }"
                >
                    <?= $heroicons->chevronDownHtml('w-4 h-4 stroke-current text-current', 16, 16) ?>
                </span>
            </h4>
            <ul class="md:block"
                x-show="open"
            >
                <li class="mb-2">
                    <a href="#" class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('Privacy')) ?>
                    </a>
                </li>
                <li class="mb-2">
                    <a href="#" class="text-xs text-current md:underline">
                        <?= $escaper->escapeHtml(__('Terms and Conditions')) ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
