<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomerRegistration;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\SvgIcons $icons */
$icons = $viewModels->require(\Hyva\Theme\ViewModel\SvgIcons::class);
?>

<div x-data="{ open: false }" class="relative inline-block">
    <button id="customer-menu"
            type="button"
            class="flex items-center h-10 rounded-3xl text-wood-light transition duration-300 ease-out hover:text-black focus:outline-none sm:px-5 xl:border xl:border-transparent xl:hover:border-white xl:hover:border-opacity-50 xl:text-white xl:hover:text-white"
            @click="open = true"
            aria-haspopup="true"
            aria-expanded="true"
            aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
    >
        <?= $icons->userHtml(
            "w-4.5 h-4.5 fill-current text-current inline-block xl:h6 xl:w-6 xl:hover:text-current",
            18,
            18
        ) ?>

        <span class="font-bold hidden ml-2 text-current sm:inline-block label">
            <?= $escaper->escapeHtml(__('My Account')) ?>
        </span>
    </button>
    <nav class="absolute right-0 z-20 hidden w-40 py-2 mt-2 -mr-4 overflow-auto origin-top-right rounded-sm
        shadow-lg sm:w-48 lg:mt-3 bg-container-lighter"
         :class="{ 'hidden' : !open }"
         @click.away="open = false"
         aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Account')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Wish List')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Orders')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Address Book')); ?></a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/logout')) ?>"
            >
                <?= $escaper->escapeHtml(__('Sign Out')); ?>
            </a>
        <?php else: ?>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>">
                <?= $escaper->escapeHtml(__('Sign In')); ?>
            </a>
            <?php
            /** @var CustomerRegistration $customerRegistration */
            $customerRegistration = $viewModels->require(CustomerRegistration::class);
            if ($customerRegistration->isAllowed()):
            ?>
                <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                   href="<?= $escaper->escapeUrl($block->getUrl('customer/account/create')) ?>"
                >
                    <?= $escaper->escapeHtml(__('Create an Account')); ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </nav>
</div>
